### ISSUE TITLE
[ENHANCEMENT] Persistence / run at startup?

### ISSUE THREAD

**Issue by eisengrau** [JonasBernard/FakeStandby#12]
Hello,

I have installed FakeStandby and added the quick tile to activate it on demand.

It would be nice, if it would be possible to enable it by default on system startup (even if root is required - actually it does not matter, for people who are using LineageOS or the sorts)?

A user case would be for people who are making other projects out of mobile devices, like for example timelapse photography, where the devices are unattended and/or remotely managed. Sometimes they need to be secheduled to be re-booted.

Thank you,

**Comment by JonasBernard** [comment]
Root is not required for this. I think, this might be an easy to implement but very helpful feature for some people. I'm looking forward to have this implemented in the next release

**Comment by JonasBernard** [comment]
Okay. The next release will contain this feature.
