### ISSUE TITLE
[ENHANCEMENT] backlight regulation

### ISSUE THREAD

**Issue by luszczyszenko** [JonasBernard/FakeStandby#16]
Hello!
Is it possible to app change screen backlight to minimum while overlay enabled? It would be another battery % saved on non-AMOLED displays.

**Comment by JonasBernard** [comment]
As far as I know, this is not pissible. Reopen the issue if you have a concrete implementation.

**Comment by luszczyszenko** [comment]
Okay. If you would like, please change the text of notification while overlay displayed. I'll use https://github.com/henrichg/PhoneProfilesPlus to detect modified notification text and set brightness to desired level. Thank you in advance.

**Comment by JonasBernard** [comment]
Thats indeed doable.

**Comment by luszczyszenko** [comment]
It would be great.
