### ISSUE TITLE
Question: Android < 11?

### ISSUE THREAD

**Issue by padrino-x** [JonasBernard/FakeStandby#40]
Wie muss ich das mit der Basis Version verstehen?
Läuft die neue Version nicht mehr mit Android 10 und kleiner? 😳

**Comment by JonasBernard** [comment]
Zweite Frage: Doch, sollte gehen.

Erste Frage: In app/build.gradle werden die targetSdkVersion (aktuell 30, entspricht Android 11, siehe apilevels.com) und minSdkVersion (23, entspricht Android 6) festgelegt.
Erstere ist die SDK Version, mit der entwickelt und getestet wird. Je höher diese Version ist, desto neuere Android Features kann die App verwenden. Im Idealfall wird die App auch für diese Version kompiliert und verbreitet (compileSdkVersion). Das heißt aber nicht, dass die fertige App nicht auf älteren oder neueren Geräten installiert und genutzt werden kann.
Die minimale Android Version, auf der die App funktioniert, wird durch minSdkVersion festgelegt. Je nach dem, welche Android Features die App verwendet, kann die minSdkVersion eher niedrig oder eher hoch gewählt werden. Entsprechend kann man FakeStandby selbst auf Android 6 installieren.
Wenn ich mich recht entsinne, wollte ich für die Quick Tiles (Schnelleinstellungen im Benachrichtigungsmenü) oder die neu eingeführten "notification channels" für Benachrichtigungen verwenden und musste daher die minSdkVersion auf 23 setzen.
Dass wir jetzt mit targetSdkVersion auf 30 stehen, liegt daran, dass ich vor habe, die App bei Google Play hochzuladen, und das ist dort (soweit ich apilevels.com verstehe) zwingend vorausgesetzt für neu hinzugefügte Apps und ab November 2022 sogar für bestehende Apps bindend.
