### ISSUE TITLE
[BUG] Not entirely blocked in landscape

### ISSUE THREAD

**Issue by JohnMertz** [JonasBernard/FakeStandby#41]
**Describe the bug**
Similar to #8, but on my device it is not necessary to rotate the device after activation.

The app ALWAYS obscures only the from the left edge to the length of the adjacent sides when in portrait mode. ie. It appears to be drawing a black overlay with the proper screen dimensions but in the opposite orientation.

**To Reproduce**
1. Have the device already in landscape mode
2. Enable FakeStandby from quick settings.
3. Screen will be only partially obscured.

**Expected behavior**
Dimensions of black overlay should match the current screen orientation so that it is fully obscured.

**Screenshots**
![Screenshot_20220804-233156_Fennec](https://user-images.githubusercontent.com/6070612/182996512-c7df45c4-f952-4f9d-8f31-5bf77420c9df.png)

**Device information:**
 - Device: Pixel 5a
 - Android Version: 11 (LineageOS)
 - App Version: 1.3.3

**Other note**
There seems to be no negative impact to having the overlay (presumably) drawn off the short edge of the screen. Perhaps just have the overlay draw with dimensions of `longest_side`×`longest_side`? This way it would not need to rotate with the screen at all. The correct edge to swipe up from is always active and works. Obviously the size may be getting cropped to fit the screen along the short edge, so this may not be a solution.

It's a simple, great app otherwise! Cheers!

**Comment by JonasBernard** [comment]
Hi and thanks for the issue.

I also had this problem on my Samsung Phone, but now it does not occur.

I already tried to solve this by setting the width and height both to max{screenWidth, screenHeight}.

Then, in landscape mode when you swipe up from the bottom, you have to swipe up for a long time before seeing the screen revealing again. This feels quite counterintuitive, so I did not commit to change.

I am thinking about locking the orientation when activating the overlay or just disabling the swipe up feature.

**Comment by KrasnayaPloshchad** [comment]
I saw there are some discussions in https://github.com/zxing/zxing/issues/576, which may give some idea.

**Comment by pythonmcpi** [comment]
In unable to reproduce this issue on a Pixel 4a running Android 13 and FakeStandby 1.3.3

**Comment by JohnMertz** [comment]
I wasn't really using the app much in the intervening time, so I tried to replicate it again. I was also not able to do so. The version of LineageOS and FakeStandby have not changed. Presumably it must be some other edge case, maybe regarding some auto-rotate settings, etc. Given that no one else seems to be seeing the issue and it's not currently impacting me, I will close.
