### ISSUE TITLE
FakeStandby stopped working in the last version (1.3.4) for my phone.

### ISSUE THREAD

**Issue by tuqueque** [JonasBernard/FakeStandby#47]
First of all, thanks for this cool, little nifty app!

**Describe the bug**
FakeStandby worked fine in my phone (Infinix Note 12, G96) in version 1.3.3 (from F-Droid), but version 1.3.4 is not working anymore. When I try to open it, it just closes immediately.

**Device information:**
 - Device: Infinix Note 12, G96.
 - Android Version: 12
 - App Version: 1.3.4 (worked fine with version 1.3.3).

Thank you in advance!

**Comment by Cyberdusker** [comment]
Hi Jonas, I find FakeStandby very useful and it worked well until a few weeks ago. But it might've started not working after I updated it through F-Droid. 

I'm using version 1.3.4 on a Samsung Galaxy A52s running Android 12.

Whenever I try turning the Standby screen on via the toggle or the app, it shows me the pop-up that says I need to turn on Accessibility settings, despite having granted every permission needed. I have activated FakeStandby as an Accessibility feature and I have granted it permission to overlay on top of screen. 

I can't figure out what the problem is, since it used to work perfectly until some time ago. I tried uninstalling it and installing it again, turning off and back on every related setting, but nothing changed.

I hope it's just a bug and that it can be fixed easily in the next update! 
Until then keep it up and thank you for the nice app!

**Comment by Ryder9013** [comment]
> Hi Jonas, I find FakeStandby very useful and it worked well until a few weeks ago. But it might've started not working after I updated it through F-Droid.
> 
> I'm using version 1.3.4 on a Samsung Galaxy A52s running Android 12.
> 
> Whenever I try turning the Standby screen on via the toggle or the app, it shows me the pop-up that says I need to turn on Accessibility settings, despite having granted every permission needed. I have activated FakeStandby as an Accessibility feature and I have granted it permission to overlay on top of screen.
> 
> I can't figure out what the problem is, since it used to work perfectly until some time ago. I tried uninstalling it and installing it again, turning off and back on every related setting, but nothing changed.
> 
> I hope it's just a bug and that it can be fixed easily in the next update! Until then keep it up and thank you for the nice app!

Same here. On Samsung M51 Android 12. I switched back to 1.3.2 (the previous version before this) and it works totally fine. In 1.3.3 either it keeps crashing on opening or keeps asking for accessibility service even though I have enabled it.

**Comment by massimostanzione** [comment]
Really useful app! And same issue on Samsung A51 Android 12, with version 1.3.4 updated through F-Droid. Accessibility settings properly set and all permissions granted, sometimes asked for cache clear, as also reported by another user in #45 . Turned on and off, restarted, cache cleared but still not working.

**Comment by Cyberdusker** [comment]
> > Hi Jonas, I find FakeStandby very useful and it worked well until a few weeks ago. But it might've started not working after I updated it through F-Droid.
> > I'm using version 1.3.4 on a Samsung Galaxy A52s running Android 12.
> > Whenever I try turning the Standby screen on via the toggle or the app, it shows me the pop-up that says I need to turn on Accessibility settings, despite having granted every permission needed. I have activated FakeStandby as an Accessibility feature and I have granted it permission to overlay on top of screen.
> > I can't figure out what the problem is, since it used to work perfectly until some time ago. I tried uninstalling it and installing it again, turning off and back on every related setting, but nothing changed.
> > I hope it's just a bug and that it can be fixed easily in the next update! Until then keep it up and thank you for the nice app!
> 
> Same here. On Samsung M51 Android 12. I switched back to 1.3.2 (the previous version before this) and it works totally fine. In 1.3.3 either it keeps crashing on opening or keeps asking for accessibility service even though I have enabled it.

Right, you reminded me that I can simply uninstall the update and go back to the previous version on F-Droid lol. Thanks, now I switched back to 1.3.2 and it works well again

**Comment by PeterKW** [comment]
Version 1.3.3 seems to be working for me now with the same problem on the newer version

https://f-droid.org/repo/android.jonas.fakestandby_10.apk
https://github.com/JonasBernard/FakeStandby/issues/55

**Comment by JonasBernard** [comment]
Can you test this with the new version 1.3.5? Still having trouble? @tuqueque @Cyberdusker @Ryder9013 @massimostanzione @PeterKW

**Comment by Ryder9013** [comment]
> Can you test this with the new version 1.3.5? Still having trouble? @tuqueque @Cyberdusker @Ryder9013 @massimostanzione @PeterKW

Yes. The app just crashes as soon as I tap the fakestandby button from notification shade icon or in the app.

**Comment by Cyberdusker** [comment]
Still having trouble. Version 1.3.3 works perfectly, while 1.3.4 and 1.3.5 have the same issue

**Comment by massimostanzione** [comment]
> Can you test this with the new version 1.3.5? Still having trouble? @tuqueque @Cyberdusker @Ryder9013 @massimostanzione @PeterKW 

Same for me - when tapping on the FakeStandby button, the app crashes or asks for Accessibility Settings, that are already properly set.

**Comment by PeterKW** [comment]
> > Can you test this with the new version 1.3.5? Still having trouble? @tuqueque @Cyberdusker @Ryder9013 @massimostanzione @PeterKW
> 
> Yes. The app just crashes as soon as I tap the fakestandby button from notification shade icon or in the app.

1.3.3 is the latest working version for me

**Comment by PeterKW** [comment]
```
FATAL EXCEPTION: main
Process: android.jonas.fakestandby, PID: 25162
java.lang.RuntimeException: Unable to start service android.jonas.fakestandby.service.AccessibilityOverlayService@97eb9c9 with Intent { cmp=android.jonas.fakestandby/.service.AccessibilityOverlayService (has extras) }: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from android.jonas.fakestandby (pid=25162, uid=10827) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4658)
	at android.app.ActivityThread.access$2000(ActivityThread.java:248)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2092)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7894)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from android.jonas.fakestandby (pid=25162, uid=10827) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5668)
	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1177)
	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:479)
	at android.jonas.fakestandby.service.AccessibilityOverlayService.g(SourceFile:4)
	at android.jonas.fakestandby.service.AccessibilityOverlayService.onStartCommand(SourceFile:7)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4640)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:2955)
	at com.android.server.wm.ActivityTaskManagerService.access$900(ActivityTaskManagerService.java:294)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:5315)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13311)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:12879)

```

**Comment by Cyberdusker** [comment]
@tuqueque True, it does. 
@JonasBernard good job, and thanks!
