### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ruiz1995724** [JonasBernard/FakeStandby#58]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device information:**
 - Device: [e.g. Galaxy S10]
 - Android Version: [e.g. 9]
 - App Version [e.g. 1.1]

**Comment by Ruiz1995724** [comment]
@JonasBernard

**Comment by JonasBernard** [comment]
This is just the template issue and does not help anything.
