### ISSUE TITLE
[BUG] Statusbar isn't hidden

### ISSUE THREAD

**Issue by Cogitri** [JonasBernard/FakeStandby#6]
**Describe the bug**
When starting fake standy the screen gets dark, but the status bar isn't hidden.

**Screenshots**
Everything in the red rectangle isn't black when activating fake standy.

![Screenshot_20200921-100205__01](https://user-images.githubusercontent.com/8766773/93744150-a7da1980-fbf1-11ea-99ba-023d2ca697bc.jpg)

**Device information:**
 - Device: Oneplus 6T
 - Android Version: 10
 - App Version: 1.2.1

**Comment by padrino-x** [comment]
I can confirm this on my Gakaxy A41 (Android 10).
Though it only seems to happen with the camera/notch area.
In landscape mode everything is covered.
If turn my phone 180° (using an rotation app) the part on the bottom (with camera) isn't covered, but status area is gone.

**Comment by JonasBernard** [comment]
Hey @Cogitri, hey @padrino-x!

This behavior is indeed caused by the notch. The issue is known, but as I do not own a phone with notch, I could not test any possible solutions for this. Sorry for that. Maybe I can compile a version that could fix the issue, and you tell me, if it worked?

**Comment by padrino-x** [comment]
Sure, if it helps I can give some beta versions a try. =)

**Comment by JonasBernard** [comment]
Another known issue is, that the navigation buttons (home, back and open apps) are not hidden by the fake standby.
I now tried to fix this and it seemed to work. In a few days I'll publish the new version to F-Droid. It MAY (!) be that this new version (1.2.2) will also fix this issue. Please tell me here, when the new version is on F-Droid.

**Comment by poppypundit** [comment]
So, will this work for IPS-LCD displays or AMOLED? The question owing to the navigation bar being displayed? 

In my case (IPS-LCD), if this is the case, I won't be saving battery.

**Comment by JonasBernard** [comment]
I recently pushed version 1.2.2 and it is already recognized by f-droid. The new version is queued for build and should be in the store in a few days.

**Comment by JonasBernard** [comment]
> So, will this work for IPS-LCD displays or AMOLED? The question owing to the navigation bar being displayed?
> 
> In my case (IPS-LCD), if this is the case, I won't be saving battery.

This is not realted to this thread. This issue is about where the app works, not what effect it has on battery life. Unfortunatly, I never tested, how much the app really safes in this case. I don't even know what a IPS-LCD display is. If you have serious doubts about that and didn't find the [disclaimer](https://github.com/JonasBernard/FakeStandby#disclaimer) in the reamde to answer all your questions, please [open a new issue](https://github.com/JonasBernard/FakeStandby/issues/new/choose).

**Comment by JonasBernard** [comment]
The versions 1.2.2 and 1.2.3 finally got released on F-Droid. Both should fix the issues described here. Can you check that?

**Comment by Cogitri** [comment]
Yup, seems to work for me, thanks!

**Comment by padrino-x** [comment]
Thanks for the reminder (somehow fdroid didn't notify me :-/).
Just got me 1.2.3 and it seems to work fine for me, too.
Thanks for the fast fix!

Now heading over to open a new issue...😇
