### ISSUE TITLE
[BUG] Problems with A30s

### ISSUE THREAD

**Issue by mecqor** [JonasBernard/FakeStandby#7]
This app has some problems with the Galaxy A30s, please fix them. Thanks

**Comment by JonasBernard** [comment]
Sorry, I cant do anything without more information. Can u give detailed insights on what problems there are?!?

**Comment by mecqor** [comment]
The status bar and navigation bar do not turn off. After a few seconds the screen turns off (as if the program does not work)

**Comment by JonasBernard** [comment]
That the status bar and navigation buttons do not turn off is a known bug, that was already fixed. In a few days the version 1.2.2 is available on f-droid.

I don't know what you mean by "the screen turns off". Does your phone enter the "real" standby mode?

**Comment by mecqor** [comment]
Yes

**Comment by JonasBernard** [comment]
Okay. I don't know, where that comes from. Which Android version do you use and what app are you in while using the app?

**Comment by mecqor** [comment]
Android 10, Telegram

**Comment by JonasBernard** [comment]
Okay thank you. I'll test if I can reproduce the issue.

Problem at the moment: testing on Android 10 does not work for me. I'll see what I can do.
